# Generated by Django 4.2.3 on 2024-02-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_menu', '0002_remove_menu_url_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='first_menu.menu'),
        ),
    ]
