# Generated by Django 4.2.3 on 2024-02-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_menu', '0003_alter_submenu_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['name'], 'verbose_name': 'Вариант меню', 'verbose_name_plural': 'Варианты меню'},
        ),
    ]
