# Generated by Django 4.2.3 on 2024-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_menu', '0004_alter_menu_options_alter_submenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название пункта'),
        ),
    ]
