# Generated by Django 4.2.3 on 2024-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_menu', '0005_submenu_about_alter_menu_name_alter_submenu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='about',
        ),
        migrations.AddField(
            model_name='submenu',
            name='fact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Интересный факт'),
        ),
    ]
