# Generated by Django 4.2.3 on 2024-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_menu', '0006_remove_submenu_about_submenu_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
