# Generated by Django 4.2.3 on 2024-02-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_menu', '0007_alter_submenu_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenu',
            old_name='fact',
            new_name='about',
        ),
    ]
