# Generated by Django 4.2.3 on 2024-02-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_menu', '0008_rename_fact_submenu_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
